



continuous_functions.pdf : continuous_functions.tex
	pdflatex continuous_functions.tex



.PHONY : clean



clean :
	rm -rf ./continuous_functions.log
	rm -rf ./continuous_functions.pdf
	rm -rf ./continuous_functions.aux
